[build]
  command = "npm ci --legacy-peer-deps && npm run netlify-build"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  CI = "false"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 