import backgroundImage from '../assets/background.jpg';

const homeStyles = {
  hero: {
    backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.7)), url(${backgroundImage})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundAttachment: 'fixed',
    color: '#fff',
    padding: 0,
    margin: 0,
    minHeight: '100vh',
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    '&:before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'radial-gradient(circle at center, rgba(183, 28, 28, 0.15) 0%, rgba(0, 0, 0, 0) 70%)',
      pointerEvents: 'none',
    },
  },
  heroContent: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: { xs: '60px 16px', md: '80px 24px' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    position: 'relative',
    zIndex: 1,
  },
  logoAvatar: {
    width: 90,
    height: 90,
    backgroundColor: 'primary.main',
    boxShadow: '0 8px 16px rgba(183, 28, 28, 0.4)',
    marginBottom: 0,
    border: '3px solid rgba(255, 255, 255, 0.2)',
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      transform: 'scale(1.1)',
      boxShadow: '0 12px 20px rgba(183, 28, 28, 0.5)',
    },
  },
  taglineContainer: {
    marginBottom: 6,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  tagChip: {
    backgroundColor: 'primary.main',
    color: 'white',
    fontWeight: 'bold',
    padding: '4px 12px',
    borderRadius: '50px',
    height: 32,
    fontSize: '0.9rem',
    boxShadow: '0 4px 8px rgba(183, 28, 28, 0.3)',
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    maxWidth: '700px',
    margin: '8px auto 40px',
    padding: '12px 24px',
    borderRadius: '50px',
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.25)',
    transition: 'all 0.3s ease-out',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 15px 35px rgba(0, 0, 0, 0.3)',
    },
  },
  searchButton: {
    borderRadius: '50px',
    padding: '10px 24px',
    fontWeight: 'bold',
    boxShadow: '0 4px 12px rgba(183, 28, 28, 0.3)',
    minWidth: '120px',
    transition: 'all 0.2s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 15px rgba(183, 28, 28, 0.4)',
    },
  },
  statsContainer: {
    marginTop: 4,
    marginBottom: 5,
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    backdropFilter: 'blur(10px)',
    padding: { xs: 3, md: 5 },
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: 'inset 0 0 30px rgba(183, 28, 28, 0.15)',
  },
  statItem: {
    textAlign: 'center',
    padding: { xs: 1.5, md: 2 },
    borderRadius: '8px',
    transition: 'transform 0.3s ease, background-color 0.3s ease',
    '&:hover': {
      transform: 'translateY(-8px)',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
    },
  },
  statIcon: {
    color: 'primary.main',
    marginBottom: 1.5,
    display: 'flex',
    justifyContent: 'center',
  },
  statValue: {
    fontWeight: 'bold',
    marginBottom: 1,
    color: 'white',
    fontSize: { xs: '1.75rem', md: '2.25rem' },
  },
  statLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: '0.95rem',
    letterSpacing: '0.5px',
  },
  divider: {
    width: '40%',
    margin: '24px auto 32px',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  actionButtons: {
    marginTop: 2,
    marginBottom: 0,
    width: '100%',
    maxWidth: { xs: '100%', sm: '500px' },
  },
  loginButton: {
    padding: '12px 30px',
    fontWeight: 'bold',
    borderRadius: '50px',
    boxShadow: '0 6px 16px rgba(183, 28, 28, 0.4)',
    minWidth: { xs: '200px', sm: '160px' },
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-3px) scale(1.03)',
      boxShadow: '0 10px 25px rgba(183, 28, 28, 0.5)',
    },
  },
  signupButton: {
    padding: '12px 30px',
    fontWeight: 'bold',
    color: 'white',
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: '50px',
    minWidth: { xs: '200px', sm: '160px' },
    borderWidth: '2px',
    transition: 'all 0.3s ease',
    '&:hover': {
      borderColor: 'white',
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      transform: 'translateY(-3px) scale(1.03)',
    },
  },
};

export default homeStyles; 